name: 'List Tex Files'
description: 'List tex files in a folder'
inputs:
  path:  # id of input
    description: 'Path to list files in'
    required: true
    default: '.'
outputs:
  files: # id of output
    description: 'The files in the folder'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}