name: Compile LaTeX documents
on: [push]
jobs:
  compile_meeting_protocols:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List Tex files
        id: texfiles
        uses: ./../.github/actions/list-tex-files
        with:
          path: Meetings/Meeting_protocols
      - name: Print tex files
        run: echo "${{ steps.texfiles.outputs.files }}"