name: Compile LaTeX documents
on: [push]
jobs:
  compile_latex_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Project_report/Project_report.tex
            Logbook/Logbook.tex
            Notes/Notes.tex
          work_in_root_file_dir: true
      - name: Commit PDF file
        uses: EndBug/add-and-commit@v9
        with:
          add: "['Project_report/Project_report.pdf', 'Logbook/Logbook.pdf', 'Notes/Notes.pdf']"
          message: 'Upload compiled PDFs'
          author_name: Compiler Bot
  compile_meeting_protocols:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Find Tex files
        id: texfiles
        uses: ./actions/ListTexFiles
        with:
          path: Meetings/Meeting_protocols
      - name: Print tex files
        run: echo "${{ steps.texfiles.outputs.files }}"