name: Compile LaTeX documents
on: [push]
jobs:
  compile_project_report:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Project_report/Project_report.tex
          work_in_root_file_dir: true
      - name: Commit PDF file
        uses: EndBug/add-and-commit@v9
        with:
          add: Project_report/Project_report.pdf
          message: 'Upload compiled PDFs'