name: Compile LaTeX documents
on: [push, pull_request]
jobs:
  compile_latex_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Project_report/Project_report.tex
            Logbook/Logbook.tex
            Notes/Notes.tex
          work_in_root_file_dir: true
      - name: Compile meeting protocols
        uses: docker://xucheng/texlive-full:latest
        with:
          run: |
            find . -name "Meetings/Meeting_protocols/*.tex" -exec latexmk -pdf -file-line-error -interaction=nonstopmode {} \;
      - name: Commit PDF file
        uses: EndBug/add-and-commit@v9
        with:
          add: "['Project_report/Project_report.pdf', 'Logbook/Logbook.pdf', 'Notes/Notes.pdf']"
          message: 'Upload compiled PDFs'
          author_name: Compiler Bot