name: Compile LaTeX documents
on: [push]
jobs:
  compile_latex_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Project_plan/Project_plan.tex
            Project_report/Project_report.tex
            Logbook/Logbook.tex
            Notes/Notes.tex
          latexmk_shell_escape: true
          work_in_root_file_dir: true
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -auxdir=../"
      
      - name: Compile minutes
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "Meetings/Minutes/*.tex"
          glob_root_file: true
          work_in_root_file_dir: true

      - name: Compile meeting notices
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "Meetings/Meeting_notices/*.tex"
          glob_root_file: true
          work_in_root_file_dir: true

      - name: Commit PDF files
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.pdf'
          message: 'Upload compiled PDFs'
          author_name: Compiler Bot
          author_email: actions@github.com
          default_author: github_actions
