name: Compile LaTeX documents
on: [push]
jobs:
  compile_latex_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            Project_report/Project_report.tex
            Logbook/Logbook.tex
            Notes/Notes.tex
          work_in_root_file_dir: true
      
  compile_meeting_protocols:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile meeting protocols
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "Meetings/Meeting_protocols/*.tex"
          glob_root_file: true
          work_in_root_file_dir: true
  
  commit_pdf_files:
    runs-on: ubuntu-latest
    needs: [compile_latex_documents, compile_meeting_protocols]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Commit PDF files
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Upload compiled PDFs'
          author_name: Compiler Bot